### PR TITLE
Switch summaries to histograms.

### PR DESCRIPTION
**Pull request by fabxc**
@grobie thoughts on the bucketing?

### CODE REVIEW

**Comment by grobie** [comment]
I'm not too much interested for accuracy above 1s and would trade the 10s for more buckets between 100-300ms. Given that this is kind of a breaking change anyway, should we go for seconds instead of microseconds as metric unit?

**Comment by fabxc** [comment]
Good point about the seconds. How about this?

**Comment by grobie** [comment]
:+1:

**Comment by grobie** [comment]
Uhm, wait. This needs some code changes when observing the actual values, no?

**Comment by fabxc** [comment]
Yep, done.

**Comment by grobie** [comment]
:+1:

**Pull request merged**
